### ISSUE TITLE
Render diverters

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-monitor#22]
Render diverters as a shape on the playfield (just like switches or lights but another shape). Turn them purple when active.

**Comment by kylenahas** [comment]
@jabdoa2, what shape would you like them to be? Triangles?

**Comment by jabdoa2** [comment]
Yeah why not. The idea was to display the state of devices such as diverters. The same may work for magnets or logic blocks.

**Comment by kylenahas** [comment]
Where would be an appropriate place to define device specific default display rules? I wouldn’t mind hardcoding them, but I think it would be neat to have it be user definable somehow (which would be useful for devices that haven’t yet been implemented in MPF). 

I’m not sure if the monitor.yaml file is or is not the place to put this. I could see the benefit of not cluttering up the already verbose file, but it’s pretty busy to begin with. 

I’d hesitate putting it in the program level config since it’s hard to access and you might not want it to be the same on every monitor project. 

My gut says monitor.yaml.

**Comment by atummons** [comment]
This is already completed. devices.py lines 138-144
